name: Build Vial QMK Firmware
on:
  workflow_dispatch: # 手動実行専用に指定し、無駄な自動テストを完全に遮断する

env:
  KEYBOARD_NAME: "stroem" # キーボードの名前
  USER_REPO_PATH: "Tamanegi-51/qmk_firmware/keyboards/stroem" # 自身のキーボードのリポジトリ名/qmk_firmware/keyboards/キーボードの名前
  FIRMWARE_VARIANT: "vial" # バリアント名

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run QMK Build Action
        uses: qmk/qmk-action@v5
        with:
          keyboard: ${{ env.KEYBOARD_NAME }}
          keymap: ${{ env.FIRMWARE_VARIANT }}
